// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpaJ09iZYYH_jsfdgxev0lCyA5J81njTI',
    appId: '1:535745644672:web:535a6ea0e535290902fe65',
    messagingSenderId: '535745644672',
    projectId: 'apps-14cdc',
    authDomain: 'apps-14cdc.firebaseapp.com',
    storageBucket: 'apps-14cdc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6i21cN_-AQNzDPZDlZ2btPZ2BI_pLsA',
    appId: '1:535745644672:android:0182e7d0b048f3cc02fe65',
    messagingSenderId: '535745644672',
    projectId: 'apps-14cdc',
    storageBucket: 'apps-14cdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGT8KuEaB6CD24YnOMPuE49gksNm5lVSo',
    appId: '1:535745644672:ios:6b49595efebb077102fe65',
    messagingSenderId: '535745644672',
    projectId: 'apps-14cdc',
    storageBucket: 'apps-14cdc.firebasestorage.app',
    iosBundleId: 'com.example.mkApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGT8KuEaB6CD24YnOMPuE49gksNm5lVSo',
    appId: '1:535745644672:ios:6b49595efebb077102fe65',
    messagingSenderId: '535745644672',
    projectId: 'apps-14cdc',
    storageBucket: 'apps-14cdc.firebasestorage.app',
    iosBundleId: 'com.example.mkApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpaJ09iZYYH_jsfdgxev0lCyA5J81njTI',
    appId: '1:535745644672:web:dbc4e60d89c250b402fe65',
    messagingSenderId: '535745644672',
    projectId: 'apps-14cdc',
    authDomain: 'apps-14cdc.firebaseapp.com',
    storageBucket: 'apps-14cdc.firebasestorage.app',
  );
}
